name: Test Suite

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php:
          - '8.3'
          - '8.4'
          - '8.5'

        laravel:
          - '12.*'
          - '13.*'

        stability:
          - prefer-lowest
          - prefer-stable

        include:
          - laravel: '12.*'
            testbench: '10.*'

          - laravel: '13.*'
            testbench: '11.*'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo, sqlite, pdo_sqlite, bcmath, intl
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --no-scripts

      - name: Run tests
        run: composer test:unit
